# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sharing is caring
email: dahfool7@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Web development blog, articles about Javascript, Css, Html and maybe Php
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: gerald_isabel
github_username:  dahfool
linkedin_url:  https://uk.linkedin.com/in/gerald-isabelle-42223288

# Build settings
markdown: kramdown
